### ISSUE TITLE
Registration Request: me

### ISSUE THREAD

**Issue by capjamesg** [link-relations/registry#61]
### Relation Name

me

### Description

Used to indicate profile equivalence and for identity-consolidation.

### Reference

https://microformats.org/wiki/rel-me and https://gmpg.org/xfn/11

### Additional Information

`rel="me"` is used on hyperlinks from one page about a person to other pages about that same person. `rel="me"` is published by many personal websites, GitHub, Mastodon, and more. Mastodon, personal websites, and more consume the standard, too.

The `rel="me"` specification was published in XFN and is maintained by the microformats community.

**Comment by evert** [comment]
Quite surprised this is not in the registry given how widespread it is!

**Comment by mnot** [comment]
It's preferable to describe the relation in term of the target resource and the link's context, so that people can understand the relationship; I'd suggest a description something like:

> Links to a resource about the author of the link's context. 

Is that OK?

Also, we can only use one link to a reference; I'd suggest the microformats one.

Finally, the additional information isn't necessary here; only critical information should appear there, and I think that in this case, the reference is sufficient.

**Comment by capjamesg** [comment]
I like that description. I would recommend the microformats reference since the microformats community is maintaining `rel=me`.

**Comment by mnot** [comment]
Thanks. I'm going to add a note to to see also the 'author' relation, and one from 'author' to 'me'.

Cheers,
